version: "3.9"
volumes:
  coupes-rases-data:
    external: false

services:
  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - coupes-rases-data:/var/lib/postgresql/data
    container_name: coupes-rases-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devuser
      DATABASES: local,test

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: coupes-rases-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://devuser:devuser@db:5432/local
